export type SubscriptionTemplate = {
  id: string;
  name: string;
  cost: number; // Monthly cost in USD
  billingCycle: "monthly" | "yearly";
  category: string;
  icon?: string; // Simple Icons identifier
  paymentMethod?: string;
  description?: string;
};

export const SUBSCRIPTION_TEMPLATES: SubscriptionTemplate[] = [
  // Streaming Services
  {
    id: "netflix",
    name: "Netflix",
    cost: 15.99,
    billingCycle: "monthly",
    category: "Streaming",
    icon: "netflix",
    paymentMethod: "Credit Card",
    description: "Streaming movies and TV shows",
  },
  {
    id: "spotify",
    name: "Spotify",
    cost: 10.99,
    billingCycle: "monthly",
    category: "Music",
    icon: "spotify",
    paymentMethod: "Credit Card",
    description: "Music streaming service",
  },
  {
    id: "youtube-premium",
    name: "YouTube Premium",
    cost: 13.99,
    billingCycle: "monthly",
    category: "Streaming",
    icon: "youtube",
    paymentMethod: "Credit Card",
    description: "Ad-free YouTube and YouTube Music",
  },
  {
    id: "appletv",
    name: "Apple TV+",
    cost: 9.99,
    billingCycle: "monthly",
    category: "Streaming",
    icon: "appletv",
    paymentMethod: "Credit Card",
    description: "Apple's streaming service",
  },
  {
    id: "hbomax",
    name: "HBO Max",
    cost: 15.99,
    billingCycle: "monthly",
    category: "Streaming",
    icon: "hbomax",
    paymentMethod: "Credit Card",
    description: "HBO and Warner Bros content",
  },
  {
    id: "disneyplus",
    name: "Disney+",
    cost: 10.99,
    billingCycle: "monthly",
    category: "Streaming",
    icon: "disneyplus",
    paymentMethod: "Credit Card",
    description: "Disney, Pixar, Marvel, and Star Wars content",
  },
  {
    id: "amazon-prime",
    name: "Amazon Prime Video",
    cost: 8.99,
    billingCycle: "monthly",
    category: "Streaming",
    icon: "amazon",
    paymentMethod: "Credit Card",
    description: "Amazon's streaming service",
  },
  {
    id: "paramount-plus",
    name: "Paramount+",
    cost: 5.99,
    billingCycle: "monthly",
    category: "Streaming",
    icon: "paramountplus",
    paymentMethod: "Credit Card",
    description: "Paramount streaming service",
  },
  {
    id: "crunchyroll",
    name: "Crunchyroll",
    cost: 7.99,
    billingCycle: "monthly",
    category: "Streaming",
    icon: "crunchyroll",
    paymentMethod: "Credit Card",
    description: "Anime streaming service",
  },
  {
    id: "hulu",
    name: "Hulu",
    cost: 7.99,
    billingCycle: "monthly",
    category: "Streaming",
    icon: "hulu",
    paymentMethod: "Credit Card",
    description: "Streaming TV shows and movies",
  },
  {
    id: "peacock",
    name: "Peacock",
    cost: 5.99,
    billingCycle: "monthly",
    category: "Streaming",
    icon: "peacock",
    paymentMethod: "Credit Card",
    description: "NBCUniversal streaming service",
  },
  {
    id: "showtime",
    name: "Showtime",
    cost: 10.99,
    billingCycle: "monthly",
    category: "Streaming",
    icon: "showtime",
    paymentMethod: "Credit Card",
    description: "Premium cable network streaming",
  },
  {
    id: "starz",
    name: "Starz",
    cost: 8.99,
    billingCycle: "monthly",
    category: "Streaming",
    icon: "starz",
    paymentMethod: "Credit Card",
    description: "Premium movie and TV streaming",
  },
  {
    id: "discovery-plus",
    name: "Discovery+",
    cost: 4.99,
    billingCycle: "monthly",
    category: "Streaming",
    icon: "discovery",
    paymentMethod: "Credit Card",
    description: "Documentary and reality TV streaming",
  },
  {
    id: "espn-plus",
    name: "ESPN+",
    cost: 10.99,
    billingCycle: "monthly",
    category: "Streaming",
    icon: "espn",
    paymentMethod: "Credit Card",
    description: "Sports streaming service",
  },
  {
    id: "amc-plus",
    name: "AMC+",
    cost: 8.99,
    billingCycle: "monthly",
    category: "Streaming",
    icon: "amc",
    paymentMethod: "Credit Card",
    description: "AMC Networks streaming service",
  },
  // Music Services
  {
    id: "applemusic",
    name: "Apple Music",
    cost: 10.99,
    billingCycle: "monthly",
    category: "Music",
    icon: "applemusic",
    paymentMethod: "Credit Card",
    description: "Apple's music streaming service",
  },
  {
    id: "tidal",
    name: "Tidal",
    cost: 10.99,
    billingCycle: "monthly",
    category: "Music",
    icon: "tidal",
    paymentMethod: "Credit Card",
    description: "High-fidelity music streaming",
  },
  {
    id: "soundcloud",
    name: "SoundCloud",
    cost: 9.99,
    billingCycle: "monthly",
    category: "Music",
    icon: "soundcloud",
    paymentMethod: "Credit Card",
    description: "Music discovery and streaming",
  },
  {
    id: "amazon-music",
    name: "Amazon Music Unlimited",
    cost: 9.99,
    billingCycle: "monthly",
    category: "Music",
    icon: "amazon",
    paymentMethod: "Credit Card",
    description: "Amazon's music streaming service",
  },
  {
    id: "deezer",
    name: "Deezer",
    cost: 10.99,
    billingCycle: "monthly",
    category: "Music",
    icon: "deezer",
    paymentMethod: "Credit Card",
    description: "Music streaming platform",
  },
  {
    id: "pandora",
    name: "Pandora Premium",
    cost: 9.99,
    billingCycle: "monthly",
    category: "Music",
    icon: "pandora",
    paymentMethod: "Credit Card",
    description: "Personalized music streaming",
  },
  // Software & Productivity
  {
    id: "adobe-creative-cloud",
    name: "Adobe Creative Cloud",
    cost: 52.99,
    billingCycle: "monthly",
    category: "Software",
    icon: "adobe",
    paymentMethod: "Credit Card",
    description: "Creative software suite",
  },
  {
    id: "microsoft-365",
    name: "Microsoft 365",
    cost: 6.99,
    billingCycle: "monthly",
    category: "Software",
    icon: "microsoft",
    paymentMethod: "Credit Card",
    description: "Office suite and cloud storage",
  },
  {
    id: "google-workspace",
    name: "Google Workspace",
    cost: 6.0,
    billingCycle: "monthly",
    category: "Software",
    icon: "google",
    paymentMethod: "Credit Card",
    description: "Google's productivity suite",
  },
  {
    id: "notion",
    name: "Notion",
    cost: 8.0,
    billingCycle: "monthly",
    category: "Productivity",
    icon: "notion",
    paymentMethod: "Credit Card",
    description: "All-in-one workspace",
  },
  {
    id: "figma",
    name: "Figma",
    cost: 12.0,
    billingCycle: "monthly",
    category: "Software",
    icon: "figma",
    paymentMethod: "Credit Card",
    description: "Design and prototyping tool",
  },
  {
    id: "github",
    name: "GitHub",
    cost: 4.0,
    billingCycle: "monthly",
    category: "Software",
    icon: "github",
    paymentMethod: "Credit Card",
    description: "Code hosting and collaboration",
  },
  {
    id: "dropbox",
    name: "Dropbox",
    cost: 9.99,
    billingCycle: "monthly",
    category: "Cloud Storage",
    icon: "dropbox",
    paymentMethod: "Credit Card",
    description: "Cloud storage and file sharing",
  },
  {
    id: "zoom",
    name: "Zoom",
    cost: 14.99,
    billingCycle: "monthly",
    category: "Productivity",
    icon: "zoom",
    paymentMethod: "Credit Card",
    description: "Video conferencing platform",
  },
  {
    id: "slack",
    name: "Slack",
    cost: 7.25,
    billingCycle: "monthly",
    category: "Productivity",
    icon: "slack",
    paymentMethod: "Credit Card",
    description: "Team communication platform",
  },
  {
    id: "canva",
    name: "Canva",
    cost: 12.99,
    billingCycle: "monthly",
    category: "Software",
    icon: "canva",
    paymentMethod: "Credit Card",
    description: "Graphic design platform",
  },
  {
    id: "grammarly",
    name: "Grammarly",
    cost: 12.0,
    billingCycle: "monthly",
    category: "Productivity",
    icon: "grammarly",
    paymentMethod: "Credit Card",
    description: "Writing assistant",
  },
  {
    id: "linear",
    name: "Linear",
    cost: 8.0,
    billingCycle: "monthly",
    category: "Productivity",
    icon: "linear",
    paymentMethod: "Credit Card",
    description: "Issue tracking and project management",
  },
  {
    id: "obsidian",
    name: "Obsidian",
    cost: 8.0,
    billingCycle: "monthly",
    category: "Productivity",
    icon: "obsidian",
    paymentMethod: "Credit Card",
    description: "Knowledge base and note-taking",
  },
  {
    id: "monday",
    name: "Monday.com",
    cost: 8.0,
    billingCycle: "monthly",
    category: "Productivity",
    icon: "monday",
    paymentMethod: "Credit Card",
    description: "Work management platform",
  },
  {
    id: "trello",
    name: "Trello",
    cost: 5.0,
    billingCycle: "monthly",
    category: "Productivity",
    icon: "trello",
    paymentMethod: "Credit Card",
    description: "Project management boards",
  },
  {
    id: "asana",
    name: "Asana",
    cost: 10.99,
    billingCycle: "monthly",
    category: "Productivity",
    icon: "asana",
    paymentMethod: "Credit Card",
    description: "Team collaboration and task management",
  },
  {
    id: "clickup",
    name: "ClickUp",
    cost: 7.0,
    billingCycle: "monthly",
    category: "Productivity",
    icon: "clickup",
    paymentMethod: "Credit Card",
    description: "All-in-one productivity platform",
  },
  {
    id: "airtable",
    name: "Airtable",
    cost: 10.0,
    billingCycle: "monthly",
    category: "Productivity",
    icon: "airtable",
    paymentMethod: "Credit Card",
    description: "Database and spreadsheet hybrid",
  },
  {
    id: "todoist",
    name: "Todoist",
    cost: 4.0,
    billingCycle: "monthly",
    category: "Productivity",
    icon: "todoist",
    paymentMethod: "Credit Card",
    description: "Task and project management",
  },
  {
    id: "evernote",
    name: "Evernote",
    cost: 8.99,
    billingCycle: "monthly",
    category: "Productivity",
    icon: "evernote",
    paymentMethod: "Credit Card",
    description: "Note-taking and organization",
  },
  {
    id: "roam-research",
    name: "Roam Research",
    cost: 15.0,
    billingCycle: "monthly",
    category: "Productivity",
    icon: "roamresearch",
    paymentMethod: "Credit Card",
    description: "Connected note-taking tool",
  },
  {
    id: "sketch",
    name: "Sketch",
    cost: 9.0,
    billingCycle: "monthly",
    category: "Software",
    icon: "sketch",
    paymentMethod: "Credit Card",
    description: "Design and prototyping tool",
  },
  {
    id: "adobe-acrobat",
    name: "Adobe Acrobat",
    cost: 22.99,
    billingCycle: "monthly",
    category: "Software",
    icon: "adobeacrobatreader",
    paymentMethod: "Credit Card",
    description: "PDF editor and creator",
  },
  {
    id: "vercel",
    name: "Vercel",
    cost: 20.0,
    billingCycle: "monthly",
    category: "Software",
    icon: "vercel",
    paymentMethod: "Credit Card",
    description: "Web hosting and deployment",
  },
  {
    id: "aws",
    name: "AWS",
    cost: 0.0, // Pay-as-you-go, but common starter estimate
    billingCycle: "monthly",
    category: "Software",
    icon: "amazonaws",
    paymentMethod: "Credit Card",
    description: "Cloud computing platform",
  },
  {
    id: "jira",
    name: "Jira",
    cost: 7.75,
    billingCycle: "monthly",
    category: "Software",
    icon: "jira",
    paymentMethod: "Credit Card",
    description: "Project and issue tracking",
  },
  // Gaming
  {
    id: "xbox-game-pass",
    name: "Xbox Game Pass",
    cost: 9.99,
    billingCycle: "monthly",
    category: "Gaming",
    icon: "xbox",
    paymentMethod: "Credit Card",
    description: "Xbox game subscription",
  },
  {
    id: "playstation-plus",
    name: "PlayStation Plus",
    cost: 9.99,
    billingCycle: "monthly",
    category: "Gaming",
    icon: "playstation",
    paymentMethod: "Credit Card",
    description: "PlayStation online service",
  },
  {
    id: "nintendo-switch-online",
    name: "Nintendo Switch Online",
    cost: 3.99,
    billingCycle: "monthly",
    category: "Gaming",
    icon: "nintendo",
    paymentMethod: "Credit Card",
    description: "Nintendo online service",
  },
  {
    id: "steam",
    name: "Steam",
    cost: 0.0, // Free, but users often have subscriptions
    billingCycle: "monthly",
    category: "Gaming",
    icon: "steam",
    paymentMethod: "Credit Card",
    description: "PC gaming platform",
  },
  {
    id: "ea-play",
    name: "EA Play",
    cost: 4.99,
    billingCycle: "monthly",
    category: "Gaming",
    icon: "ea",
    paymentMethod: "Credit Card",
    description: "Electronic Arts game subscription",
  },
  {
    id: "ubisoft-plus",
    name: "Ubisoft+",
    cost: 14.99,
    billingCycle: "monthly",
    category: "Gaming",
    icon: "ubisoft",
    paymentMethod: "Credit Card",
    description: "Ubisoft game subscription",
  },
  // Security & VPN
  {
    id: "nordvpn",
    name: "NordVPN",
    cost: 11.99,
    billingCycle: "monthly",
    category: "Security",
    icon: "nordvpn",
    paymentMethod: "Credit Card",
    description: "VPN service",
  },
  {
    id: "1password",
    name: "1Password",
    cost: 2.99,
    billingCycle: "monthly",
    category: "Security",
    icon: "1password",
    paymentMethod: "Credit Card",
    description: "Password manager",
  },
  {
    id: "lastpass",
    name: "LastPass",
    cost: 3.0,
    billingCycle: "monthly",
    category: "Security",
    icon: "lastpass",
    paymentMethod: "Credit Card",
    description: "Password manager",
  },
  {
    id: "bitwarden",
    name: "Bitwarden",
    cost: 3.0,
    billingCycle: "monthly",
    category: "Security",
    icon: "bitwarden",
    paymentMethod: "Credit Card",
    description: "Password manager",
  },
  // Other
  {
    id: "audible",
    name: "Audible",
    cost: 7.95,
    billingCycle: "monthly",
    category: "Entertainment",
    icon: "audible",
    paymentMethod: "Credit Card",
    description: "Audiobook service",
  },
  {
    id: "icloud",
    name: "iCloud+",
    cost: 0.99,
    billingCycle: "monthly",
    category: "Cloud Storage",
    icon: "icloud",
    paymentMethod: "Credit Card",
    description: "Apple cloud storage",
  },
  {
    id: "google-drive",
    name: "Google Drive",
    cost: 1.99,
    billingCycle: "monthly",
    category: "Cloud Storage",
    icon: "googledrive",
    paymentMethod: "Credit Card",
    description: "Google cloud storage",
  },
  {
    id: "onedrive",
    name: "OneDrive",
    cost: 1.99,
    billingCycle: "monthly",
    category: "Cloud Storage",
    icon: "microsoft",
    paymentMethod: "Credit Card",
    description: "Microsoft cloud storage",
  },
  {
    id: "box",
    name: "Box",
    cost: 5.0,
    billingCycle: "monthly",
    category: "Cloud Storage",
    icon: "box",
    paymentMethod: "Credit Card",
    description: "Cloud content management",
  },
  {
    id: "pcloud",
    name: "pCloud",
    cost: 4.99,
    billingCycle: "monthly",
    category: "Cloud Storage",
    icon: "pcloud",
    paymentMethod: "Credit Card",
    description: "Cloud storage service",
  },
  // News & Media
  {
    id: "nytimes",
    name: "The New York Times",
    cost: 17.0,
    billingCycle: "monthly",
    category: "News",
    icon: "thenewyorktimes",
    paymentMethod: "Credit Card",
    description: "Digital news subscription",
  },
  {
    id: "wsj",
    name: "The Wall Street Journal",
    cost: 28.99,
    billingCycle: "monthly",
    category: "News",
    icon: "wsj",
    paymentMethod: "Credit Card",
    description: "Financial news subscription",
  },
  {
    id: "medium",
    name: "Medium",
    cost: 5.0,
    billingCycle: "monthly",
    category: "News",
    icon: "medium",
    paymentMethod: "Credit Card",
    description: "Article and story platform",
  },
  {
    id: "substack",
    name: "Substack",
    cost: 5.0,
    billingCycle: "monthly",
    category: "News",
    icon: "substack",
    paymentMethod: "Credit Card",
    description: "Newsletter subscription platform",
  },
  // Fitness & Health
  {
    id: "peloton",
    name: "Peloton",
    cost: 12.99,
    billingCycle: "monthly",
    category: "Fitness",
    icon: "peloton",
    paymentMethod: "Credit Card",
    description: "Fitness classes and workouts",
  },
  {
    id: "strava",
    name: "Strava",
    cost: 11.99,
    billingCycle: "monthly",
    category: "Fitness",
    icon: "strava",
    paymentMethod: "Credit Card",
    description: "Running and cycling tracking",
  },
  {
    id: "myfitnesspal",
    name: "MyFitnessPal Premium",
    cost: 9.99,
    billingCycle: "monthly",
    category: "Fitness",
    icon: "myfitnesspal",
    paymentMethod: "Credit Card",
    description: "Nutrition and fitness tracking",
  },
  {
    id: "nike-training",
    name: "Nike Training Club",
    cost: 9.99,
    billingCycle: "monthly",
    category: "Fitness",
    icon: "nike",
    paymentMethod: "Credit Card",
    description: "Workout and training app",
  },
  // Food & Delivery
  {
    id: "hellofresh",
    name: "HelloFresh",
    cost: 59.99,
    billingCycle: "monthly",
    category: "Food",
    icon: "hellofresh",
    paymentMethod: "Credit Card",
    description: "Meal kit delivery service",
  },
  {
    id: "blue-apron",
    name: "Blue Apron",
    cost: 59.99,
    billingCycle: "monthly",
    category: "Food",
    icon: "blueapron",
    paymentMethod: "Credit Card",
    description: "Meal kit delivery service",
  },
  {
    id: "instacart",
    name: "Instacart Express",
    cost: 9.99,
    billingCycle: "monthly",
    category: "Food",
    icon: "instacart",
    paymentMethod: "Credit Card",
    description: "Grocery delivery service",
  },
  {
    id: "doordash",
    name: "DoorDash DashPass",
    cost: 9.99,
    billingCycle: "monthly",
    category: "Food",
    icon: "doordash",
    paymentMethod: "Credit Card",
    description: "Food delivery subscription",
  },
  {
    id: "uber-eats",
    name: "Uber Eats Pass",
    cost: 9.99,
    billingCycle: "monthly",
    category: "Food",
    icon: "ubereats",
    paymentMethod: "Credit Card",
    description: "Food delivery subscription",
  },
  // Education & Learning
  {
    id: "masterclass",
    name: "MasterClass",
    cost: 15.0,
    billingCycle: "monthly",
    category: "Education",
    paymentMethod: "Credit Card",
    description: "Online classes from experts",
  },
  {
    id: "skillshare",
    name: "Skillshare",
    cost: 32.0,
    billingCycle: "monthly",
    category: "Education",
    icon: "skillshare",
    paymentMethod: "Credit Card",
    description: "Online learning platform",
  },
  {
    id: "duolingo",
    name: "Duolingo Plus",
    cost: 6.99,
    billingCycle: "monthly",
    category: "Education",
    icon: "duolingo",
    paymentMethod: "Credit Card",
    description: "Language learning app",
  },
  {
    id: "coursera",
    name: "Coursera Plus",
    cost: 59.0,
    billingCycle: "monthly",
    category: "Education",
    icon: "coursera",
    paymentMethod: "Credit Card",
    description: "Online course platform",
  },
  // Professional & Business
  {
    id: "linkedin",
    name: "LinkedIn Premium",
    cost: 29.99,
    billingCycle: "monthly",
    category: "Professional",
    icon: "linkedin",
    paymentMethod: "Credit Card",
    description: "Professional networking platform",
  },
  {
    id: "salesforce",
    name: "Salesforce",
    cost: 25.0,
    billingCycle: "monthly",
    category: "Software",
    icon: "salesforce",
    paymentMethod: "Credit Card",
    description: "CRM and business platform",
  },
  {
    id: "hubspot",
    name: "HubSpot",
    cost: 20.0,
    billingCycle: "monthly",
    category: "Software",
    icon: "hubspot",
    paymentMethod: "Credit Card",
    description: "Marketing and sales platform",
  },
];

/**
 * Get template by ID
 */
export function getTemplateById(id: string): SubscriptionTemplate | undefined {
  return SUBSCRIPTION_TEMPLATES.find((template) => template.id === id);
}

/**
 * Get templates grouped by category
 */
export function getTemplatesByCategory(): Record<
  string,
  SubscriptionTemplate[]
> {
  const grouped: Record<string, SubscriptionTemplate[]> = {};

  SUBSCRIPTION_TEMPLATES.forEach((template) => {
    if (!grouped[template.category]) {
      grouped[template.category] = [];
    }
    grouped[template.category].push(template);
  });

  return grouped;
}

/**
 * Get all unique categories
 */
export function getCategories(): string[] {
  const categories = new Set(SUBSCRIPTION_TEMPLATES.map((t) => t.category));
  return Array.from(categories).sort();
}
